name: x

default_ecosystem: avalanche

avalanche:
  default_network: fuji
  fuji:
    default_provider: geth
    #gas_limit: max
    gas_limit: auto

geth:
  avalanche:
    fuji:
      uri: https://api.avax-test.network/ext/bc/C/rpc

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5

plugins:
  - name: avalanche
  - name: solidity

solidity:
  version: 0.8.18
